name: Build and publish docs

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        # python-version: [ 3.7, 3.8]
        python-version: [ 3.8]


    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # pip install -r requirements.txt
          pip install diagrams
          sudo apt install graphviz
      - name: Build diagram
        run: |
          python test.py
      - name: Get diagram files
        uses: actions/upload-artifact@v2
        with:
          name: diagrams
          path: *.png

